# Haystack RAG Application Configuration

# Elasticsearch settings
elasticsearch:
  url: "http://elasticsearch:9200"
  user: "elastic"
  password: "YourSecurePass123!"

# Qdrant settings
qdrant:
  url: "http://qdrant:6333"
  collection_name: "semantic_search"

# MySQL settings
mysql:
  host: "mysql"
  user: "root"
  password: "rootpassword"
  database: "wrag"
  port: 3306
  enabled: true

# LLM settings
llm:
  generator: "ollama"
  use_ollama: true
  ollama_api_url: "http://ollama:11434"
  ollama_models:
    - "deepseek-r1:1.5b"
    - "deepseek-r1:7b" 

# Embedding settings
embedding:
  model: "intfloat/multilingual-e5-base"
  dim: 768

# Document processing settings
document:
  split_by: "word"
  split_length: 250
  split_overlap: 30

# Application settings
app:
  index_on_startup: false
  pipelines_from_yaml: false

# Logging settings
logging:
  level: "INFO"
  haystack_level: "INFO"
  tokenizers_parallelism: false

# Tracing settings
tracing:
  enabled: true
  jaeger_host: "jaeger"
  jaeger_port: 6831
  content_enabled: false

# Metrics settings
metrics:
  enabled: true
  prometheus_exporter: true
  service_name: "wrag-app"

# Docker and build settings
docker:
  ollama_models:
    - "deepseek-r1:1.5b"
    - "deepseek-r1:7b" 