services:
  # Base image service - added to ensure the base image is built automatically
  base:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile.base
    image: wrag-app-base:latest
    # This service will exit immediately after building the image
    command: [ "echo", "Base image built successfully" ]
    restart: "no"

  nginx:
    platform: linux/amd64
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-9090}:8080"
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      indexing_service:
        condition: service_healthy
      query_service:
        condition: service_healthy
      frontend:
        condition: service_started
      elasticsearch:
        condition: service_healthy
      qdrant:
        condition: service_started
    restart: on-failure

  indexing_service:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile.indexing
    depends_on:
      elasticsearch:
        condition: service_healthy
      ollama:
        condition: service_started
      qdrant:
        condition: service_started
      mysql:
        condition: service_healthy
      jaeger:
        condition: service_started
    ports:
      - "${INDEXING_PORT:-8001}:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_API_URL=http://ollama:${OLLAMA_PORT:-11434}
    volumes:
      - file-storage:/app/files
      - ./backend/src/pipelines:/app/pipelines
      - ./config.yml:/app/config.yml
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/health" ]
      interval: 10s
      timeout: 5s
      retries: 18
      start_period: 30s

  query_service:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile.query
    depends_on:
      elasticsearch:
        condition: service_healthy
      ollama:
        condition: service_started
      qdrant:
        condition: service_started
      mysql:
        condition: service_healthy
      jaeger:
        condition: service_started
    ports:
      - "${QUERY_PORT:-8002}:8002"
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_API_URL=http://ollama:${OLLAMA_PORT:-11434}
    volumes:
      - file-storage:/app/files
      - ./backend/src/pipelines:/app/pipelines
      - ./config.yml:/app/config.yml
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8002/health" ]
      interval: 10s
      timeout: 5s
      retries: 18
      start_period: 30s

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        - REACT_APP_WRAG_API_URL=${WRAG_API_URL:-/api}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./nginx/nginx-frontend.conf:/etc/nginx/conf.d/default.conf:ro
    restart: on-failure

  elasticsearch:
    image: elasticsearch:8.12.1
    platform: linux/amd64
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT:-9201}:9200"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=wrag
      - MYSQL_USER=wrag
      - MYSQL_PASSWORD=wrag
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  kibana:
    image: kibana:8.12.1
    platform: linux/amd64
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              count: all
              driver: nvidia

  qdrant:
    image: qdrant/qdrant:v1.13.2
    volumes:
      - qdrant-data:/qdrant/storage
    ports:
      - "${QDRANT_HTTP_PORT:-6333}:6333"
      - "${QDRANT_GRPC_PORT:-6334}:6334"
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "${JAEGER_UI_PORT:-16686}:16686" # UI
      - "${JAEGER_OTLP_GRPC_PORT:-4317}:4317" # OTLP gRPC
      - "${JAEGER_THRIFT_PORT:-6831}:6831/udp" # Jaeger thrift
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=memory
      - SAMPLING_STRATEGIES_FILE=/etc/jaeger/sampling_strategies.json
    volumes:
      - ./jaeger-sampling.json:/etc/jaeger/sampling_strategies.json
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:16686" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  prometheus:
    image: prom/prometheus:v2.48.1
    ports:
      - "${PROMETHEUS_PORT:-9091}:9090" # Prometheus UI (External:Internal)
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:9090/-/healthy" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - "${GRAFANA_PORT:-3001}:3000" # Grafana UI (External:Internal)
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      prometheus:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s

volumes:
  mysql-data:
  elasticsearch-data:
  qdrant-data:
  prometheus-data:
  grafana-data:
  file-storage:
  ollama_data:
