{{- if .Values.gkeGateway.enabled }}
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ include "app.fullname" . }}-gcp-be-policy
spec:
  default:
    timeoutSec: 600
  targetRef:
    group: ""
    kind: Service
    name: {{ include "app.fullname" . }}-{{ index .Values.gkeGateway.routes 0 "service" }}  # TODO: ???
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gke-gw
spec:
  gatewayClassName: gke-l7-regional-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: gke-gw
  {{- if .Values.gkeGateway.hosts }}
  hostnames:
  {{- range .Values.gkeGateway.hosts }}
  - {{ .host }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.gkeGateway.routes }}
  - matches:
    - path:
        type: PathPrefix
        value: {{ .path }}
    backendRefs:
    - name: {{ include "app.fullname" $ }}-{{ .service }}
      port: {{ .port }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
  {{- end }}
{{- end }}
