{{- if not .Values.global.secrets.useExternalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secrets
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  opensearch-user: {{ .Values.global.secrets.opensearch.adminUser | b64enc }}
  opensearch-password: {{ .Values.global.secrets.opensearch.adminPassword | b64enc }}
  openai-api-key: {{ .Values.global.secrets.openai.apiKey | b64enc }}
{{- end }}
