global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'indexing_service'
    static_configs:
      - targets: ['indexing_service:8001']
    metrics_path: '/metrics'

  - job_name: 'query_service'
    static_configs:
      - targets: ['query_service:8002']
    metrics_path: '/metrics'
    
  - job_name: 'haystack_components'
    static_configs:
      - targets: ['indexing_service:8001', 'query_service:8002']
    metrics_path: '/metrics'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'haystack_component.*'
        action: keep

# Enable out-of-order ingestion
storage:
  tsdb:
    out_of_order_time_window: 30m 